baseURL = "http://iyaja.github.io/pay-attention-to-attention/"
languageCode = "en-us"
title = "Pay Attention to Attention!"
publishDir = "docs"

theme = "reveal-hugo"

[params.reveal_hugo]
theme = "night"


[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true
